### ISSUE TITLE
[feature] Support for command-line way to get galaxy information on current role folder

### ISSUE THREAD

**Issue by fubarhouse** [ansible/galaxy#1140]
### Use Case
The command line option `ansible-galaxy` does not appear to work for roles outside of the scope of what is in a role folder. When a role is being developed or maintained and local tools are being used to help - there's no way for the folder to be identified as an Ansible Galaxy role by any means and no information is available until pushed via source control.

### Proposed Solution
Options for use would ideally encourage or force developers to maintain two separate key/value pairs in `meta/main.yml` to contain the owner's user name and the role name as identified in Galaxy. `ansible-galaxy` should by extension be able to know who the role belongs to and what the role is - even if it means identifying with the use of git hashes for integrity.

### Alternatives
I'm still exploring, but there's no consistent and reliable method to do this now. I have found specific key/value pairs which are quite inconsistent and impractical when it comes to searching for this information via scripts.

### Implementation
Implementation I believe would simply contain two strongly encouraged or forced key/value pairs in `meta/main.yml` to contain the user name of the owner and the role name as identified by Ansible Galaxy. An example of what this could look like is below, please note the emphasis of the command being run (`ansible-galaxy info .` - where `.` represents a relative or absolute path to a folder which contains a role):

```
 08:08 PM:~/Projects/Ansible/Curl $ ansible-galaxy info .

Role: fubarhouse.curl
        description: Installs Curl from desired released source code
        active: True
        commit: 9ebd2b085c01fa9e860195137338cf6c8ef8be11
        commit_message: Merge pull request #21 from fubarhouse/issue-18

PR for #18
        commit_url: https://api.github.com/repos/fubarhouse/ansible-role-curl/git/commits/9ebd2b085c01fa9e860195137338cf6c8ef8be11
        company: 
        created: 2016-11-11T13:00:14.768456Z
        dependencies: []
        download_count: 3124
        forks_count: 3
        galaxy_info:
                author: Karl Hepworth
                galaxy_tags: ['curl', 'system', 'essential', 'wget']
                license: MIT
                min_ansible_version: 2.0
                platforms: [{'name': 'Fedora', 'versions': [24, 25, 26]}, {'name': 'Ubuntu', 'versions': ['artful', 'zesty', 'yakkety', 'xenial', 'vivid', 'wily', 'utopic', '
        github_branch: master
        github_repo: ansible-role-curl
        github_user: fubarhouse
        id: 13298
        imported: 2018-09-03T08:55:46.542266-04:00
        install_date: Sat Dec 30 01:13:29 2017
        intalled_version: 1.6.0
        is_valid: True
        issue_tracker_url: https://github.com/fubarhouse/ansible-role-curl/issues
        license: MIT
        min_ansible_version: 2.4
        modified: 2018-09-03T12:55:46.542473Z
        open_issues_count: 6
        path: [u'/Users/karl/.ansible/roles', u'/usr/share/ansible/roles', u'/etc/ansible/roles']
        role_type: ANS
        stargazers_count: 0
        travis_status_url: https://travis-ci.org/fubarhouse/ansible-role-curl.svg?branch=1.6.1
 08:13 PM:~/Projects/Ansible/Curl $
```

### My need for this
I maintain [Ansible Role Tester](https://github.com/fubarhouse/ansible-role-tester), and one thing we've found a need for is to mount the role folder which is being actively changed and tested by the developer in a docker container. That folder should ideally be in folder understood by Ansible to be in the convention `user_name.role_name`, in which we're attempting to replicate.
