### ISSUE TITLE
Additional platform definitions in Galaxy

### ISSUE THREAD

**Issue by stealthllama** [ansible/galaxy#1448]
### Use Case
New network and virtualization platform definitions are needed in Galaxy in order to properly categorize roles affecting them.

### Proposed Solution
Add the following platforms to the Galaxy database:

```
galaxy_info:
  platforms:
    - name: PAN-OS
      versions:
        - 7.1
        - 8.0
        - 8.1
        - 9.0
    - name: vSphere
      versions:
        - 5.5
        - 6.0
        - 6.5
        - 6.7
    - name: vCenter
      versions:
        - 5.5
        - 6.0
        - 6.5
        - 6.7
    - name: TMOS
      versions:
        - 12.1
        - 13.0
        - 13.1
        - 14.0
```

### Alternatives
n/a

### Implementation
n/a
