### ISSUE TITLE
IMPORTER101: Invalid platform: "Fedora-30", skipping.

### ISSUE THREAD

**Issue by dallinb** [ansible/galaxy#1926]
##### SUMMARY
Getting a drop in Metadata score for my role with the following message:

```IMPORTER101: Invalid platform: "Fedora-30", skipping.```

##### STEPS TO REPRODUCE
The platforms section of `meta/main.yml` looks like this:

```YAML
  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - stretch
    - name: Fedora
      versions:
        - 29
        - 30
```

##### EXPECTED RESULTS
Fedora 30 final release was 2019-05-07 (see https://fedoraproject.org/wiki/Releases/30/Schedule).

##### ACTUAL RESULTS
The message

```
IMPORTER101: Invalid platform: "Fedora-30", skipping.
```
is currently visible at https://galaxy.ansible.com/locp/cassandra
