### ISSUE TITLE
collection allowed to have role(s) with - in the role name

### ISSUE THREAD

**Issue by chrismeyersfsu** [ansible/galaxy#1969]
##### SUMMARY
Galaxy allows me to publish a collection containing a role with a `-` in it's name.  The docs state that role should not contain `-` https://galaxy.ansible.com/docs/contributing/creating_collections.html#role-names

This causes inconsistent behavior in Ansible which I will attempt to explain.

##### STEPS TO REPRODUCE
```
- hosts: localhost
  gather_facts: false
  roles:
    - chrismeyersfsu.test_things.debug-variable
```
The above results in the error `ERROR! the role 'chrismeyersfsu.test_things.debug_variable' was not found in `

The below succeeds
```
- hosts: localhost
  gather_facts: false
  collections:
    - chrismeyersfsu.test_things
  roles:
    - debug-variable
```

When I rename my role to `debug_variable` both call patterns work, as expected.
