### ISSUE TITLE
Test against CentOS 8

### ISSUE THREAD

**Issue by 14rcole** [ansible/galaxy#2067]
CentOS 8 was released on September 24th so we're a bit behind on this

**Comment by chouseknecht** [comment]
CentOS is considered Enterprise Linux. So for CentOS 8, you'll use the following:

```
galaxy_info:
...
  platforms:
  - name: EL
    versions:
    - 8
```
