### ISSUE TITLE
CentOS and RHEL are not the same, the platform "EL" does cover both.

### ISSUE THREAD

**Issue by robertdebock** [ansible/galaxy#2072]
### Use Case

The current `meta/main.yml` currently has `EL` as a platform name:

```yaml
---
galaxy_info:
...
  platforms:
  - name: EL
    versions:
    - 8
---

That's not enough to target `RHEL` **or** `CentOS`. They differ slightly. In some cases a role can fail on RHEL 8, but work on CentOS 8, still there is only one identifier that I can use to indicate where this role works on.

### Proposed Solution

I think a split should be okay:
- `EL` is an indicator for both `RHEL` and `CentOS`.
- `CentOS` or `RHEL` are subsets of EL, but usable as a platform.

So this would be possible:
```yaml
---
galaxy_info:
...
  platforms:
  - name: CentOS
    versions:
    - 7
    - 8
  - name: RHEL
    versions:
    - 7
```

This would be an invalid specification; EL indicates both RHEL and CentOS:
```yaml
---
galaxy_info:
...
  platforms:
  - name: EL
    versions:
    - 7
    - 8
  - name: RHEL
    versions:
    - 7
```
### Alternatives
None.

### Implementation
As a contributor of Ansible roles I would like to be able to target specific distributions like CentOS or RHEL in order to specify that some role only work on specific distributions.

**Comment by chouseknecht** [comment]
You're advocating for more platforms. I would advocate for none, and we move this whole nightmare to some sort of tag.

**Comment by robertdebock** [comment]
I agree, maybe just tags in `galaxy_info.galaxy_tags` can be used for that.

What would be cool, if `galaxy_info` would contain some data that indicates where the role can be tested on. Say something like this:

```yaml
---
galaxy_info:
  test_on:
    containers:
      - image: centos
        tag: latest
    virtual_machines:
      - vagrant_box: ubuntu/trusty64
        version: 20190429.0.1
```

With such a structure galaxy could test the role and advertise that it's been tested on several platforms.

For now, I think I will move stuff to tags.
