### ISSUE TITLE
IMPORTER101: Invalid platform: "Fedora-31", skipping.

### ISSUE THREAD

**Issue by dallinb** [ansible/galaxy#2105]
##### SUMMARY
Getting a drop in Metadata score for my role with the following message:

`IMPORTER101: Invalid platform: "Fedora-31", skipping.`

Similar to #1926

##### STEPS TO REPRODUCE
The platforms section of `meta/main.yml` looks like this:

```YAML
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - buster
        - stretch
    - name: Fedora
      versions:
        - 27
        - 28
        - 29
        - 30
        - 31
```

##### EXPECTED RESULTS
Fedora 31 has been released (see https://fedoraproject.org/wiki/Releases/31/Schedule)

##### ACTUAL RESULTS
https://galaxy.ansible.com/locp/cassandra shows the following message:

```
IMPORTER101: Invalid platform: "Fedora-31", skipping.
```
