### ISSUE TITLE
Ansible Galaxy playbook wrapper for roles/collections

### ISSUE THREAD

**Issue by m-czernek** [ansible/galaxy#2128]
## Feature Request
On [1], I can browse various roles and collections. I'd like a button for each particular role, that would generate a playbook utilizing the role. For example, for [2], there would be a button to download a zip archive with the following contents:

**playbook.yml**
```yaml
- hosts: all 
  gather_facts: yes 

  roles:
    - geerlingguy.apache
```

**requirements.yml**
```
- src: geerlingguy.apache
```

This would be a good beginning. A change to the UI could be that the author would input an example variable file into a special field, which would then get copied into the playbook. For example:

**playbook.yml**
```yaml
- hosts: all 
  gather_facts: yes 

  vars:
     var_specified_by_author: "foo"

  roles:
    - geerlingguy.apache
```

[1] https://galaxy.ansible.com
[2] https://galaxy.ansible.com/geerlingguy/apache

### Use Case

It would definitely help with the getting started experience. The feature should be relatively easy to implement, and would help users to generate usable playbook wrappers for roles.

WDYT?
