### ISSUE TITLE
ansible-lint warnings can't be whitelisted

### ISSUE THREAD

**Issue by chkpnt** [ansible/galaxy#2270]
##### SUMMARY
ansible-lint on Galaxy doesn't seem to respect the `# noqa [rule]` statements.

##### STEPS TO REPRODUCE
In [this example](https://github.com/chkpnt/chkpnt-mailserver/blob/bd6e282a613f709ce864d93f70dcc0326092026e/tasks/setup-apparmor.yml#L3-L8), ansible-lint reports a false-positive: the module `systemd` can't be used as a replacement for my `systemctl is-enabled apparmor.service` shell command (rule 303 and 305).

```yaml
- name: Is AppArmor active?
  block:
    - shell: systemctl is-enabled apparmor.service # noqa 303 305 502
      register: systemstatus_apparmor
    - set_fact: # noqa 502
        apparmor_active: "{{ systemstatus_apparmor.stdout == 'enabled' }}"
```
Furthermore, I do not want to name the tasks in a block (rule 502).

Therefore I'm defining the appropriate `# noqa [rule]` macros to skip the rules at the concerned lines.

##### EXPECTED RESULTS
No warnings for the whitelisted linter issues when importing the role.

##### ACTUAL RESULTS
On my local machine, I don't get the warnings when executing `ansible-lint`. In contrast, Galaxy still reports the warnings:
```
Starting import: task_id=583173, repository=chkpnt/chkpnt-mailserver 
[...]
===== LINTING ROLE: mailserver ===== 
yamllint OK. 
ansible-lint Warnings: 
[...]
./galaxy/imports/tmpu4rjh5bx/tasks/setup-apparmor.yml:5: [E303] systemctl used in place of systemd module 
./galaxy/imports/tmpu4rjh5bx/tasks/setup-apparmor.yml:5: [E305] Use shell only when shell functionality is required 
./galaxy/imports/tmpu4rjh5bx/tasks/setup-apparmor.yml:5: [E502] All tasks should be named 
./galaxy/imports/tmpu4rjh5bx/tasks/setup-apparmor.yml:7: [E502] All tasks should be named 
[...]
```
