### ISSUE TITLE
Have skip-tags listed in playbook

### ISSUE THREAD

**Issue by zedth2** [ansible/galaxy#2459]
### Use Case
Wanting to skip specific DISA STIG tagged in [redhatofficial.rhel7_stig](https://galaxy.ansible.com/RedHatOfficial/rhel7_stig)

### Proposed Solution
In the playbook it would be nice to have a skip_tags key that takes a list. In the same fashion that the CLI for ansible-playbook switch --skip-tags works.

### Alternatives
Currently the only other way I can come up with a way to do this is keep a bash script with --skip-tags filled out, which kind of defeats the point of having a playbook. Or just maintaining my own copy of rhel7_stig with the things I don't want commented out.

### Implementation
```yaml
---
- hosts: super-private-hosts
  roles:
    - redhatofficial.rhel7_stig
  skip_tags:
    - DISA-STIG-RHEL-07-040180 # Because I have no LDAP
```

### Caveat
I'm really new to Ansible so if I missed something please let me know. Thanks for making my life easier though!

....I just realized I'm definitely in the wrong repo. Sorry about that
