### ISSUE TITLE
IMPORTER101: Invalid platform: "Fedora-33", skipping.

### ISSUE THREAD

**Issue by dallinb** [ansible/galaxy#2533]
##### SUMMARY
Getting a drop in Metadata score for my role with the following message:

`IMPORTER101: Invalid platform: "Fedora-33", skipping.`

##### STEPS TO REPRODUCE
The platforms section of meta/main.yml looks like this:

```YAML
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
    - name: Debian
      versions:
        - buster
        - stretch
    - name: Fedora
      versions:
        - 27
        - 28
        - 29
        - 30
        - 31
        - 32
        - 33
```

##### EXPECTED RESULTS
Fedora 33 final release was 2020-10-27 (see https://fedorapeople.org/groups/schedule/f-33/f-33-key-tasks.html).

##### ACTUAL RESULTS
The message:

`IMPORTER101: Invalid platform: "Fedora-33", skipping.`

is currently visible at https://galaxy.ansible.com/locp/cassandra
