### ISSUE TITLE
IMPORTER101: Invalid platform: "Ubuntu-hirsute", skipping.

### ISSUE THREAD

**Issue by httpdop** [ansible/galaxy#2759]
##### SUMMARY
Getting a drop in Metadata score for my role with the following message:

IMPORTER101: Invalid platform: "Ubuntu-hirsute", skipping.

##### STEPS TO REPRODUCE
The platforms section of meta/main.yml looks like this:
```
platforms:
    - name: Ubuntu
      versions:
        - hirsute
        - focal
        - bionic
        - groovy
```

##### EXPECTED RESULTS
The message:

Ubuntu 21.04 Hirsute Hippo release was 2021-04-22 (see https://wiki.ubuntu.com/Releases)

##### ACTUAL RESULTS
IMPORTER101: Invalid platform: "Ubuntu-hirsute", skipping.

is currently visible at https://galaxy.ansible.com/httpdop/linux_wireguard
