### ISSUE TITLE
add FreeBSD 12.2, 12.3, 13, OpenBSD 6.9, 7.0 platforms

### ISSUE THREAD

**Issue by nusenu** [ansible/galaxy#2803]
same as previously #73, #172, #280, #705, #2170, #1585, #2174, #2398, #2478

```
    Invalid platform: "FreeBSD-12.2", skipping.
    Invalid platform: "FreeBSD-13.0", skipping.
    Invalid platform: "OpenBSD-6.9", skipping
```

ref
#80

**Comment by nvjacobo** [comment]
Hi, 

I have the same issue

```
Invalid platform: "FreeBSD-13.0", skipping.
Invalid platform: "FreeBSD-12.2", skipping. 
```
meta.yml 

```
  platforms:
   - name: Debian
     versions:
     - buster
     - bullseye
   - name: Ubuntu
     versions:
     - focal
   - name: FreeBSD
     versions:
     - 13.0
     - 12.2
```
Thanks, Jacobo
