### ISSUE TITLE
IMPORTER101: Invalid platform: "Ubuntu-jammy", skipping

### ISSUE THREAD

**Issue by jfhovinne** [ansible/galaxy#2918]
##### SUMMARY

Ubuntu Jammy has been released and should be added to the list of platforms.

https://wiki.ubuntu.com/Releases

https://galaxy.ansible.com/api/v1/platforms/?name=Ubuntu

##### STEPS TO REPRODUCE

meta/main.yml platforms section:

```
---
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
```

##### EXPECTED RESULTS

Release "jammy" added and valid.

##### ACTUAL RESULTS

```
IMPORTER101: Invalid platform: "Ubuntu-jammy", skipping.
```

Thanks.
