### ISSUE TITLE
ansible.galaxy.com returning HTTP code 503

### ISSUE THREAD

**Issue by markafarrell** [ansible/galaxy#2938]
##### SUMMARY
Ansible Galaxy site broken

##### STEPS TO REPRODUCE

Navigate to https://galaxy.ansible.com in browser

##### EXPECTED RESULTS
Ansible galaxy website loads

##### ACTUAL RESULTS

Ansible galaxy website fails to load

![image](https://user-images.githubusercontent.com/8586761/170611399-a6f19b81-132a-4b43-a0a8-53c92195141b.png)

Ansible galaxy cli tool also fails

```
ansible-galaxy collection install community.general
Process install dependency map
ERROR! Error when finding available api versions from default (https://galaxy.ansible.com) (HTTP Code: 530, Message: )
```

**Comment by mdebord-dlr** [comment]
**Same issue here.** 

For anyone else with CI/CD issues because of this, I am just working around it by bypassing Galaxy completely in `requirements.yaml` ... 

Example....

Instead of this: 
```
collections:
  - name: "amazon.aws"
    version: "3.2.0"
```

Do this: 
```
collections:
  - name: "https://github.com/ansible-collections/amazon.aws"
    version: "3.2.0"
    type: "git"
```
