### ISSUE TITLE
No Monterey macOS support in Galaxy

### ISSUE THREAD

**Issue by lotyp** [ansible/galaxy#2939]
##### SUMMARY

Currently there is limited support for platforms to provide in meta file:
Can we add Monterey support to versions array?

```
  "macOS": {
    "name": "macOS",
    "versions": [
      "Big-Sur",
      "High-Sierra",
      "Sierra"
    ]
  },
```

##### STEPS TO REPRODUCE

meta.yml

```
  platforms:
    - name: macOS
      versions:
        - "Monterey"
```

##### EXPECTED RESULTS
Should support Monterey

##### ACTUAL RESULTS
Will throw error saying about unsupported platform.
