### ISSUE TITLE
Time to time https://galaxy.ansible.com responds 500 code

### ISSUE THREAD

**Issue by dmitryrode** [ansible/galaxy#2954]
##### SUMMARY
Time to time https://galaxy.ansible.com responds 500 code, when I am try to run `ansible-galaxy install`. 

##### STEPS TO REPRODUCE

`ansible-galaxy install -r requirements.yml`
```
cat requirements.yml
collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: 4.1.0
    source: https://galaxy.ansible.com
```
##### EXPECTED RESULTS

```
Downloading https://galaxy.ansible.com/download/community-general-4.1.0.tar.gz to /.ansible/tmp/ansible-local-63565ah3koefe/tmpbvam948_/community-general-4.1.0-ymiv5b9z
Installing 'community.general:4.1.0' to 'ansible_collections/community/general'
 community.general:4.1.0 was installed successfully
Downloading https://galaxy.ansible.com/download/ansible-posix-1.3.0.tar.gz to /.ansible/tmp/ansible-local-63565ah3koefe/tmpbvam948_/ansible-posix-1.3.0-07rf0ktk
Installing 'ansible.posix:1.3.0' to 'ansible_collections/ansible/posix'
ansible.posix:1.3.0 was installed successfully
Downloading https://galaxy.ansible.com/download/openstack-cloud-1.5.3.tar.gz to /.ansible/tmp/ansible-local-63565ah3koefe/tmpbvam948_/openstack-cloud-1.5.3-dftxevgk
Installing 'openstack.cloud:1.5.3' to 'ansible_collections/openstack/cloud'
```

##### ACTUAL RESULTS

`ERROR! Error when finding available api versions from default (https://galaxy.ansible.com/) (HTTP Code: 500, Message: Internal Server Error)`
