### ISSUE TITLE
Misleading error: unrecognized arguments: -r requirements.yml

### ISSUE THREAD

**Issue by Mawarii** [ansible/galaxy#3021]
##### SUMMARY
ansible-galaxy throws a misleading error. It tells you "ansible: error: unrecognized arguments: -r requirements.yml", but actually the collection is depricated/removed.

##### STEPS TO REPRODUCE
- You need ansible 6.0.0 or newer
- Create requirements.yml file with the following content:
```
collections:
  - name: community.kubernetes
    version: 2.0.1
    source: https://galaxy.ansible.com
```
- run `ansible-galaxy install -r requirements.yml`

##### EXPECTED RESULTS
With ansible 6.0.0 and newer it should tell you that community.kubernetes is depricated and can't be installed because it was removed.

##### ACTUAL RESULTS
ansible: error: unrecognized arguments: -r requirements.yml
