### ISSUE TITLE
Invalid platform: "Fedora-37", skipping.

### ISSUE THREAD

**Issue by coglinev3** [ansible/galaxy#3152]
##### SUMMARY
Ansible-Galaxy API generates an error when importing any role that supports Fedora 37.

```
Checking role metadata tags
Checking role platforms
Invalid platform: "Fedora-37", skipping.
```

##### STEPS TO REPRODUCE
Create a platform section in `meta/main.yml` like this one:

```yaml
platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
    - name: Fedora
      versions:
        - "34"
        - "35"
        - "36"
        - "37"
```

##### EXPECTED RESULTS

The import should work without errors, since Fedora 37 was already released on 11/15/2022.

##### ACTUAL RESULTS

Import error:
```
Invalid platform: "Fedora-37", skipping.
```
Searching using the Galaxy API reveals that Fedora Release 37 is not supported:
https://galaxy.ansible.com/api/v1/platforms/?page=3&search=Fedora

The last supported Fedora version is 36.

```http
GET /api/v1/platforms/?page=3&search=Fedora
```

```json
HTTP 200 OK
  Allow: GET, HEAD, OPTIONS
  Content-Type: application/json
  Vary: Accept

  {
    "count": 21,
    "next": null,
    "next_link": null,
    "previous": "[/platforms/?page=2&search=Fedora](https://galaxy.ansible.com/platforms/?page=2&search=Fedora)",
    "previous_link": "[/api/v1/platforms/?page=2&search=Fedora](https://galaxy.ansible.com/api/v1/platforms/?page=2&search=Fedora)",
    "results": [
        {
            "id": 244,
            "url": "[/api/v1/platforms/244/](https://galaxy.ansible.com/api/v1/platforms/244/)",
            "related": {},
            "summary_fields": {},
            "created": "2021-09-23T14:24:19.377044Z",
            "modified": "2021-09-23T14:24:19.377074Z",
            "name": "Fedora",
            "release": "36",
            "active": true
        }
    ]
}
```
##### Note
Fedora Release 38 will be released next Tuesday, 04/18/2023, which also means that Fedora Release 36 will then have reached End of Life.
Therefore, it makes sense for the Galaxy API to support Fedora Release 38 at the same time as Fedora Release 37.
