### ISSUE TITLE
Roles namespace has changed with the new Galaxy website

### ISSUE THREAD

**Issue by btravouillon** [ansible/galaxy#3253]
##### SUMMARY

Our namespace **mila** was created in #2792.

Since then, people are using `mila.<collection_name>` and `mila.<role_name>` to install our roles and collections.

```
---
roles:
  - name: mila.bareos
    version: 1.5.0

  - name: mila.cobbler
    version: v0.2.2

  - name: mila.cobbler
    version: v0.3.3

collections:
  - name: mila.proxmox
    version: 0.5.2
```

Previously, we were able to see our published content with a **single** URL (https://galaxy.ansible.com/mila).

Today, there are three URLs, one for the collections and two others for the roles. 

- Collections : https://galaxy.ansible.com/ui/namespaces/mila/
- Roles : https://galaxy.ansible.com/ui/standalone/namespaces/4653/ -> The namespace for the roles is incorrect. It matches the (legacy) name of our GitHub organization, but not the name we are using with Ansible Galaxy.
- Roles : https://galaxy.ansible.com/ui/standalone/namespaces/9418/ -> Has our content but links to a GitHub account which is not our organization.

##### STEPS TO REPRODUCE

Access to https://galaxy.ansible.com/mila/ -> you are redirected to the home page

Search for "clockwork" in the roles : this will return two results with the same content. If you enter the official role (https://galaxy.ansible.com/ui/standalone/roles/mila/clockwork/) and click on **[Github Repository](https://github.com/mila/ansible-role-clockwork)**, you'll get a 404.

##### EXPECTED RESULTS

I expect to see all the published content (roles and collections) in the same page (https://galaxy.ansible.com/ui/namespaces/mila/ or even better https://galaxy.ansible.com/mila/ for backward compatibility).

If that's not possible with the NG version, I would at least expect to get a coherent namespace which is **mila**.

##### ACTUAL RESULTS

![image](https://github.com/ansible/galaxy/assets/14249095/feede318-7f40-4ae1-a421-d399859cf342)
