### ISSUE TITLE
"role install" leads to collection being cloned for scm sourced collections

### ISSUE THREAD

**Issue by Yannik** [ansible/galaxy#3361]
##### SUMMARY
I have a `requirements.yml` like this (minimal reproducable example):

```
roles:
 - name: firewalld
   src: git+ssh://git@gitlab.xxx/ansible/roles/firewalld.git

collections:
 - name: git+ssh://git@gitlab.xxx/ansible/collections/kraktorist.figlet
```

Now I want to update/re-download the firewalld role to get the latest version.

For this, I am using: `ansible-galaxy role install -r requirements.yml --force firewalld`

##### EXPECTED RESULTS
Only firewalld should be downloaded.

##### ACTUAL RESULTS
The firewalld role is downloaded, but so are all configured collections (in this case, kraktorist.figlet):

```
Cloning into '/home/yannik/.ansible/tmp/ansible-local-939490subk6doi/tmpt67t3k8_/kraktorist.figletxwjih159'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 11 (delta 0), reused 5 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (11/11), 4.86 KiB | 4.86 MiB/s, done.
Your branch is up to date with 'origin/master'.
Starting galaxy role install process
- changing role firewalld from  to unspecified
- extracting firewalld to /home/yannik/projects/xxx/ansible/vendor_roles/firewalld
- firewalld was installed successfully
```
