### ISSUE TITLE
Import error when I try to define a custom name for a role dependency

### ISSUE THREAD

**Issue by achaussier** [ansible/galaxy#514]
Hello,

Today I test conditional dependencies for my roles, but I want to use a pattern for the downloads:
```
<role_name>__<role_version>
```

When I try to use the same syntax than requirements.yml in meta/main.yml, this not work:
```
dependencies:
  - src: 'infOpen.curl'
    version: '0.1.0'
    name: 'infOpen.curl__0.1.0'
    when: "halyard_use_ansible_galaxy_dependencies or _use_role_dependencies"
```
I have an error when I try an import:
> Error parsing dependency Role dependency not found: infOpen.curl__0.1.0

The parsing step check the custom name after download by galaxy instead the role source name.

Thanks
