### ISSUE TITLE
Support for more platforms in the meta file.

### ISSUE THREAD

**Issue by sbaerlocher** [ansible/galaxy#882]
### Use Case
In the platform information in galaxy_info only Windows Server 2012R2 is supported for Windows systems. Meanwhile there are also Windows 10 and Windows Server 2016 and soon Windows Server 2019. I would suggest to add the other Windows operating systems in galaxy_info platforms.

### Proposed Solution
Added the possibility to specify version 10 and 2016 or 2019 respectively.

#### Example
```yml
galaxy_info:
  platforms:
    - name: Windows
      versions:
        - 10
        - 2016
        - 2019
```

### Alternatives
N/A

### Implementation
N/A
